"""
Domain Enums for the Gate Entry module.
"""
from enum import Enum


class GateEntryStatus(str, Enum):
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    PO_VERIFIED = "PO_VERIFIED"
    FIELD_MISMATCH_DETECTED = "FIELD_MISMATCH_DETECTED"
    MANUAL_VERIFICATION_REQUIRED = "MANUAL_VERIFICATION_REQUIRED"
    APPROVED = "APPROVED"
    GATE_ENTRY_APPROVED = "GATE_ENTRY_APPROVED"
    AWAITING_DOCK = "AWAITING_DOCK"
    DOCK_ASSIGNED = "DOCK_ASSIGNED"
    MOVING_TO_DOCK = "MOVING_TO_DOCK"
    AT_DOCK = "AT_DOCK"
    OCCUPIED = "OCCUPIED"
    UNLOADING_IN_PROGRESS = "UNLOADING_IN_PROGRESS"
    QUALITY_INSPECTION_REQUIRED = "QUALITY_INSPECTION_REQUIRED"
    QUALITY_PASSED = "QUALITY_PASSED"
    QUALITY_FAILED = "QUALITY_FAILED"
    RECEIVING_COMPLETED = "RECEIVING_COMPLETED"
    COMPLETED = "COMPLETED"
    RELEASED = "RELEASED"
    DOCK_RELEASED = "RELEASED"
    EXIT_APPROVED = "EXIT_APPROVED"
    GATE_EXIT_COMPLETED = "GATE_EXIT_COMPLETED"
    VEHICLE_EXITED = "VEHICLE_EXITED"
    REJECTED = "REJECTED"
    UNSCHEDULED_ARRIVAL = "UNSCHEDULED_ARRIVAL"
    CHECKED_IN = "CHECKED_IN"
    UNLOADED = "UNLOADED"
    CHECKED_OUT = "CHECKED_OUT"
    DENIED_ENTRY = "DENIED_ENTRY"


class MismatchField(str, Enum):
    PO_NUMBER = "po_number"
    SUPPLIER_NAME = "supplier_name"
    PRODUCT_MATERIAL = "product_material"
    QUANTITY = "quantity"
    PO_DATE = "po_date"
    EXPECTED_DELIVERY_DATE = "expected_delivery_date"


class VerificationResultType(str, Enum):
    MATCHED = "MATCHED"
    MISMATCHED = "MISMATCHED"
    LOW_ANPR_CONFIDENCE = "LOW_ANPR_CONFIDENCE"
    UNSCHEDULED_PO = "UNSCHEDULED_PO"
    FAILED_OCR = "FAILED_OCR"
    FAILED_ANPR = "FAILED_ANPR"
