"""
Repository ports for procurement module.
Defines abstract Protocol methods for saving and fetching aggregates.
"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.modules.procurement.domain.asn import ASN
from app.modules.procurement.domain.arrival_notification import ArrivalNotification
from app.modules.procurement.domain.quotation import Quotation
from app.modules.procurement.domain.rfq import RFQ
from app.modules.procurement.domain.supplier import Supplier
from app.modules.procurement.domain.value_objects import (
    AsnId,
    PurchaseOrderId,
    QuotationId,
    RfqId,
    SupplierId,
)


class SupplierRepository(Protocol):
    async def find_by_id(self, supplier_id: SupplierId) -> Optional[Supplier]: ...

    async def list_all(self) -> List[Supplier]: ...

    async def exists_by_gstin(self, gstin: str, exclude_id: Optional[str] = None) -> bool: ...
    async def exists_by_company_name(self, name: str, exclude_id: Optional[str] = None) -> bool: ...
    async def exists_by_email(self, email: str, exclude_id: Optional[str] = None) -> bool: ...
    async def exists_by_phone(self, phone: str, exclude_id: Optional[str] = None) -> bool: ...
    async def exists_by_bank_account(self, account_number: str, exclude_id: Optional[str] = None) -> bool: ...
    async def exists_by_swift(self, swift: str, exclude_id: Optional[str] = None) -> bool: ...
    async def get_next_sequence(self) -> int: ...

    async def save(self, supplier: Supplier) -> None:
        """Persists the Supplier aggregate."""
        ...


class RfqRepository(Protocol):
    async def save(self, rfq: RFQ) -> None: ...
    async def get_by_id(self, rfq_id: RfqId) -> Optional[RFQ]: ...
    async def list_all(self) -> List[RFQ]: ...
    async def get_next_sequence(self, year: int) -> int: ...


class QuotationRepository(Protocol):
    async def save(self, quotation: Quotation) -> None: ...
    async def get_by_id(self, quotation_id: QuotationId) -> Optional[Quotation]: ...
    async def list_all(self) -> List[Quotation]: ...


class AsnRepository(Protocol):
    async def save(self, asn: ASN) -> None: ...
    async def get_by_id(self, asn_id: AsnId) -> Optional[ASN]: ...
    async def get_by_po_id(self, po_id: PurchaseOrderId) -> List[ASN]: ...
    async def list_all(self) -> List[ASN]: ...
    async def get_next_sequence(self, year: int) -> int: ...


class ArrivalNotificationRepository(Protocol):
    async def save(self, notification: ArrivalNotification) -> None: ...
    async def get_by_id(self, notification_id: str) -> Optional[ArrivalNotification]: ...
    async def list_all(self) -> List[ArrivalNotification]: ...


class MaterialRequestRepository(Protocol):
    async def get_next_sequence(self, year_month: str) -> int: ...


