from enum import Enum


class DockType(str, Enum):
    RAW_MATERIAL = "RAW_MATERIAL"
    CHEMICAL_HAZARDOUS = "CHEMICAL_HAZARDOUS"
    ELECTRICAL = "ELECTRICAL"
    CHEMICAL = "CHEMICAL"
    HAZARDOUS_ITEMS = "HAZARDOUS_ITEMS"
    ELECTRONICS = "ELECTRONICS"
    MAIN_RECEIVING = "MAIN_RECEIVING"


class DockStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    OCCUPIED = "OCCUPIED"
    MAINTENANCE = "MAINTENANCE"
    INACTIVE = "INACTIVE"


class AllocationStatus(str, Enum):
    PENDING_ALLOCATION = "PENDING_ALLOCATION"
    AWAITING_DOCK = "AWAITING_DOCK"
    DOCK_ASSIGNED = "DOCK_ASSIGNED"
    RESERVED = "RESERVED"
    OCCUPIED = "OCCUPIED"
    COMPLETED = "COMPLETED"
    RELEASED = "RELEASED"
    CANCELLED = "CANCELLED"


class AllocationPriority(str, Enum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class AllocationAction(str, Enum):
    REQUESTED = "REQUESTED"
    ALLOCATED = "ALLOCATED"
    REASSIGNED = "REASSIGNED"
    ARRIVED = "ARRIVED"
    RECEIVING_STARTED = "RECEIVING_STARTED"
    COMPLETED = "COMPLETED"
    RELEASED = "RELEASED"
    CANCELLED = "CANCELLED"
