"""add procurement workflow tables

Revision ID: 6dd90401f80c
Revises: 8811455d5036
Create Date: 2026-08-12 19:49:27.240250
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database.base import GUID


revision: str = '6dd90401f80c'
down_revision: Union[str, None] = '8811455d5036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisition',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition'))
    )
    op.create_table('purchase_requisition_line',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('requisition_id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisition.id'], name=op.f('fk_purchase_requisition_line_requisition_id_purchase_requisition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition_line'))
    )
    op.create_table('rfq',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('pr_id', GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisition.id'], name=op.f('fk_rfq_pr_id_purchase_requisition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rfq'))
    )
    op.create_table('quotation',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('rfq_id', GUID(length=36), nullable=False),
    sa.Column('supplier_id', GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], name=op.f('fk_quotation_rfq_id_rfq')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_quotation_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation'))
    )
    op.create_table('rfq_supplier_link',
    sa.Column('rfq_id', GUID(length=36), nullable=False),
    sa.Column('supplier_id', GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], name=op.f('fk_rfq_supplier_link_rfq_id_rfq')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_rfq_supplier_link_supplier_id_supplier')),
    sa.PrimaryKeyConstraint('rfq_id', 'supplier_id', name=op.f('pk_rfq_supplier_link'))
    )
    op.create_table('quotation_line',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('quotation_id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], name=op.f('fk_quotation_line_quotation_id_quotation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotation_line'))
    )
    op.create_table('asn',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('po_id', GUID(length=36), nullable=False),
    sa.Column('asn_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vehicle_number', sa.String(length=64), nullable=True),
    sa.Column('driver_name', sa.String(length=128), nullable=True),
    sa.Column('driver_contact', sa.String(length=32), nullable=True),
    sa.Column('expected_arrival_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], name=op.f('fk_asn_po_id_purchase_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asn')),
    sa.UniqueConstraint('asn_number', name=op.f('uq_asn_asn_number'))
    )
    op.create_table('asn_line',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('asn_id', GUID(length=36), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('shipped_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asn.id'], name=op.f('fk_asn_line_asn_id_asn')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asn_line'))
    )
    op.add_column('purchase_order', sa.Column('quotation_id', GUID(length=36), nullable=True))
    op.add_column('purchase_order', sa.Column('supplier_id', GUID(length=36), nullable=True))
    op.add_column('purchase_order', sa.Column('status', sa.String(length=32), nullable=False, server_default='OPEN'))
    op.add_column('purchase_order', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.execute("""
        INSERT INTO supplier (id, supplier_name, registered_company_name, vendor_type, category, industry, gstin, remarks, status)
        SELECT '00000000-0000-0000-0000-000000000001', 'Legacy Supplier', 'Legacy Supplier',
               'LEGACY', 'General', 'General', 'LEGACY', 'Created while migrating legacy purchase orders', 'Active'
        WHERE NOT EXISTS (SELECT 1 FROM supplier)
    """)
    op.execute("""
        UPDATE purchase_order
        SET supplier_id = (SELECT id FROM supplier ORDER BY id LIMIT 1)
        WHERE supplier_id IS NULL
    """)
    op.execute("UPDATE purchase_order SET po_date = CURRENT_DATE WHERE po_date IS NULL")
    op.alter_column('purchase_order', 'supplier_id', nullable=False)
    op.alter_column('purchase_order', 'po_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_foreign_key(op.f('fk_purchase_order_supplier_id_supplier'), 'purchase_order', 'supplier', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('fk_purchase_order_quotation_id_quotation'), 'purchase_order', 'quotation', ['quotation_id'], ['id'])
    op.add_column('purchase_order_line', sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_line', 'unit_price')
    op.drop_constraint(op.f('fk_purchase_order_quotation_id_quotation'), 'purchase_order', type_='foreignkey')
    op.drop_constraint(op.f('fk_purchase_order_supplier_id_supplier'), 'purchase_order', type_='foreignkey')
    op.alter_column('purchase_order', 'po_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('purchase_order', 'created_at')
    op.drop_column('purchase_order', 'status')
    op.drop_column('purchase_order', 'supplier_id')
    op.drop_column('purchase_order', 'quotation_id')
    op.drop_table('asn_line')
    op.drop_table('asn')
    op.drop_table('quotation_line')
    op.drop_table('rfq_supplier_link')
    op.drop_table('quotation')
    op.drop_table('rfq')
    op.drop_table('purchase_requisition_line')
    op.drop_table('purchase_requisition')
    # ### end Alembic commands ###
