"""add supplier_id to asn

Revision ID: 8c4c48db6de0
Revises: 32be34494663
Create Date: 2026-08-15 10:46:16.918053
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.database.base

revision: str = '8c4c48db6de0'
down_revision: Union[str, None] = '32be34494663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material'))
    )
    op.create_index(op.f('ix_material_code'), 'material', ['code'], unique=True)
    op.create_table('supplier_material_link',
    sa.Column('supplier_id', app.database.base.GUID(length=36), nullable=False),
    sa.Column('material_id', app.database.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_supplier_material_link_material_id_material'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_material_link_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supplier_id', 'material_id', name=op.f('pk_supplier_material_link'))
    )
    conn = op.get_bind()
    conn.execute(sa.text("DROP TABLE IF EXISTS purchase_requisition_line CASCADE"))
    conn.execute(sa.text("DROP TABLE IF EXISTS purchase_requisition CASCADE"))
    conn.execute(sa.text("ALTER TABLE asn ADD COLUMN IF NOT EXISTS shipment_date DATE DEFAULT CURRENT_DATE"))
    conn.execute(sa.text("ALTER TABLE asn ADD COLUMN IF NOT EXISTS supplier_id UUID"))
    op.alter_column('asn', 'po_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('asn', 'shipment_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_constraint(op.f('uq_asn_asn_number'), 'asn', type_='unique')
    op.create_index(op.f('ix_asn_asn_number'), 'asn', ['asn_number'], unique=True)
    op.create_foreign_key(op.f('fk_asn_supplier_id_supplier'), 'asn', 'supplier', ['supplier_id'], ['id'])
    op.add_column('grn', sa.Column('po_number', sa.String(length=64), nullable=True))
    op.alter_column('grn', 'po_id',
               existing_type=sa.UUID(),
               nullable=True)
    conn.execute(sa.text("ALTER TABLE rfq ADD COLUMN IF NOT EXISTS rfq_number VARCHAR(64)"))
    conn.execute(sa.text("ALTER TABLE rfq ADD COLUMN IF NOT EXISTS rfq_date DATE DEFAULT CURRENT_DATE"))
    conn.execute(sa.text("ALTER TABLE rfq ADD COLUMN IF NOT EXISTS warehouse VARCHAR(128)"))
    conn.execute(sa.text("ALTER TABLE rfq ADD COLUMN IF NOT EXISTS procurement_officer VARCHAR(128)"))
    op.alter_column('rfq', 'rfq_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('rfq', 'rfq_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('rfq', 'warehouse',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('rfq', 'procurement_officer',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    conn.execute(sa.text("ALTER TABLE supplier ADD COLUMN IF NOT EXISTS rating NUMERIC(3,2) DEFAULT 0"))
    conn.execute(sa.text("ALTER TABLE supplier ADD COLUMN IF NOT EXISTS performance_score NUMERIC(5,2) DEFAULT 0"))
    conn.execute(sa.text("ALTER TABLE supplier ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP"))
    conn.execute(sa.text("ALTER TABLE supplier ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP"))
    op.alter_column('supplier', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('supplier', 'performance_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('supplier', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supplier', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supplier', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supplier', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('supplier', 'performance_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('supplier', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('rfq', 'procurement_officer',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('rfq', 'warehouse',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('rfq', 'rfq_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('rfq', 'rfq_number',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('grn', 'po_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('grn', 'po_number')
    op.drop_constraint(op.f('fk_asn_supplier_id_supplier'), 'asn', type_='foreignkey')
    op.drop_index(op.f('ix_asn_asn_number'), table_name='asn')
    op.create_unique_constraint(op.f('uq_asn_asn_number'), 'asn', ['asn_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('asn', 'shipment_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('asn', 'po_id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('asn', 'supplier_id')
    op.create_table('purchase_requisition',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition'))
    )
    op.create_table('purchase_requisition_line',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requisition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('estimated_unit_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisition.id'], name=op.f('fk_purchase_requisition_line_requisition_id_purchase_re_72b9')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition_line'))
    )
    op.drop_table('supplier_material_link')
    op.drop_index(op.f('ix_material_code'), table_name='material')
    op.drop_table('material')
    # ### end Alembic commands ###
