"""add_procurement_supplier_tables_fixed

Revision ID: aad1bed9d1aa
Revises: 0006
Create Date: 2026-08-12 10:18:30.872491
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aad1bed9d1aa'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=128), nullable=False),
    sa.Column('registered_company_name', sa.String(length=256), nullable=False),
    sa.Column('vendor_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('gstin', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_table('supplier_address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('pincode', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_address_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_address'))
    )
    op.create_table('supplier_bank_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('account_holder_name', sa.String(length=128), nullable=True),
    sa.Column('ifsc', sa.String(length=32), nullable=True),
    sa.Column('branch', sa.String(length=128), nullable=True),
    sa.Column('swift_bic', sa.String(length=32), nullable=True),
    sa.Column('tds_section', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_bank_info_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_bank_info'))
    )
    op.create_table('supplier_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_contact_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_contact'))
    )
    op.create_table('supplier_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_supplier_document_supplier_id_supplier'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_document'))
    )
    op.alter_column('gate_entry', 'driver_photo_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_index(op.f('idx_gate_entry_po_number'), table_name='gate_entry')
    op.drop_index(op.f('idx_gate_entry_status'), table_name='gate_entry')
    op.drop_index(op.f('idx_gate_entry_vehicle_number'), table_name='gate_entry')
    op.create_index(op.f('ix_gate_entry_po_number'), 'gate_entry', ['po_number'], unique=False)
    op.create_index(op.f('ix_gate_entry_status'), 'gate_entry', ['status'], unique=False)
    op.create_index(op.f('ix_gate_entry_vehicle_number'), 'gate_entry', ['vehicle_number'], unique=False)
    op.drop_index(op.f('idx_outbox_undelivered'), table_name='outbox_event')
    op.drop_constraint(op.f('uq_purchase_order_po_number'), 'purchase_order', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_purchase_order_po_number'), 'purchase_order', ['po_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_outbox_undelivered'), 'outbox_event', ['delivered', 'occurred_at'], unique=False)
    op.drop_index(op.f('ix_gate_entry_vehicle_number'), table_name='gate_entry')
    op.drop_index(op.f('ix_gate_entry_status'), table_name='gate_entry')
    op.drop_index(op.f('ix_gate_entry_po_number'), table_name='gate_entry')
    op.create_index(op.f('idx_gate_entry_vehicle_number'), 'gate_entry', ['vehicle_number'], unique=False)
    op.create_index(op.f('idx_gate_entry_status'), 'gate_entry', ['status'], unique=False)
    op.create_index(op.f('idx_gate_entry_po_number'), 'gate_entry', ['po_number'], unique=False)
    op.alter_column('gate_entry', 'driver_photo_path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_table('supplier_document')
    op.drop_table('supplier_contact')
    op.drop_table('supplier_bank_info')
    op.drop_table('supplier_address')
    op.drop_table('supplier')
    # ### end Alembic commands ###
