"""add_status_to_supplier

Revision ID: f4897dcf5268
Revises: aad1bed9d1aa
Create Date: 2026-08-12 10:45:52.874130
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4897dcf5268'
down_revision: Union[str, None] = 'aad1bed9d1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('status', sa.String(length=32), nullable=False, server_default='Pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'status')
    # ### end Alembic commands ###
