/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssemblyDashboardRouteImport } from './routes/assembly-dashboard'
import { Route as DamageClaimsRouteImport } from './routes/damage-claims'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as DispatchDriversRouteImport } from './routes/dispatch-drivers'
import { Route as DispatchExceptionsRouteImport } from './routes/dispatch-exceptions'
import { Route as DispatchGateExitRouteImport } from './routes/dispatch-gate-exit'
import { Route as DispatchGateOutRouteImport } from './routes/dispatch-gate-out'
import { Route as DispatchLoadingRouteImport } from './routes/dispatch-loading'
import { Route as DispatchOrdersRouteImport } from './routes/dispatch-orders'
import { Route as DispatchPickingPackingRouteImport } from './routes/dispatch-picking-packing'
import { Route as DispatchPodRouteImport } from './routes/dispatch-pod'
import { Route as DispatchReportsRouteImport } from './routes/dispatch-reports'
import { Route as DispatchTransitRouteImport } from './routes/dispatch-transit'
import { Route as DispatchTransportAllocationRouteImport } from './routes/dispatch-transport-allocation'
import { Route as DispatchVehiclesRouteImport } from './routes/dispatch-vehicles'
import { Route as DockManagementRouteImport } from './routes/dock-management'
import { Route as DockMasterRouteImport } from './routes/dock-master'
import { Route as GateDashboardRouteImport } from './routes/gate-dashboard'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerDashboardRouteImport } from './routes/manager-dashboard'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as MyStoreRouteImport } from './routes/my-store'
import { Route as NewSupplierRouteImport } from './routes/new-supplier'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PutawayTasksRouteImport } from './routes/putaway-tasks'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplierDashboardRouteImport } from './routes/supplier-dashboard'
import { Route as UnscheduledArrivalsRouteImport } from './routes/unscheduled-arrivals'
import { Route as VehicleExitRouteImport } from './routes/vehicle-exit'
import { Route as VehicleQueueRouteImport } from './routes/vehicle-queue'
import { Route as WarehouseDashboardRouteImport } from './routes/warehouse-dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AssemblyFinishedGoodsRouteImport } from './routes/assembly.finished-goods'
import { Route as AssemblyMaterialRequestsRouteImport } from './routes/assembly.material-requests'
import { Route as AssemblyOrdersRouteImport } from './routes/assembly.orders'
import { Route as AssemblyProductionRouteImport } from './routes/assembly.production'
import { Route as AssemblyQualityRouteImport } from './routes/assembly.quality'
import { Route as AssemblyRequestsRouteImport } from './routes/assembly.requests'
import { Route as PoCodeRouteImport } from './routes/po.$code'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as WarehouseAssemblyRequisitionsRouteImport } from './routes/warehouse.assembly-requisitions'
import { Route as WarehouseDispatchTrackingRouteImport } from './routes/warehouse.dispatch-tracking'
import { Route as WarehouseFinishedGoodsRequestsRouteImport } from './routes/warehouse.finished-goods-requests'
import { Route as WarehouseFinishedGoodsStoreRouteImport } from './routes/warehouse.finished-goods-store'
import { Route as WarehouseMaterialRequestsRouteImport } from './routes/warehouse.material-requests'
import { Route as WarehouseMaterialsRouteImport } from './routes/warehouse.materials'
import { Route as WarehouseQuarantineRouteImport } from './routes/warehouse.quarantine'
import { Route as WarehouseStoresRouteImport } from './routes/warehouse.stores'
import { Route as SupplierAsnsNewRouteImport } from './routes/supplier.asns.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyDashboardRoute = AssemblyDashboardRouteImport.update({
  id: '/assembly-dashboard',
  path: '/assembly-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageClaimsRoute = DamageClaimsRouteImport.update({
  id: '/damage-claims',
  path: '/damage-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchDriversRoute = DispatchDriversRouteImport.update({
  id: '/dispatch-drivers',
  path: '/dispatch-drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchExceptionsRoute = DispatchExceptionsRouteImport.update({
  id: '/dispatch-exceptions',
  path: '/dispatch-exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchGateExitRoute = DispatchGateExitRouteImport.update({
  id: '/dispatch-gate-exit',
  path: '/dispatch-gate-exit',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchGateOutRoute = DispatchGateOutRouteImport.update({
  id: '/dispatch-gate-out',
  path: '/dispatch-gate-out',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchLoadingRoute = DispatchLoadingRouteImport.update({
  id: '/dispatch-loading',
  path: '/dispatch-loading',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchOrdersRoute = DispatchOrdersRouteImport.update({
  id: '/dispatch-orders',
  path: '/dispatch-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchPickingPackingRoute = DispatchPickingPackingRouteImport.update({
  id: '/dispatch-picking-packing',
  path: '/dispatch-picking-packing',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchPodRoute = DispatchPodRouteImport.update({
  id: '/dispatch-pod',
  path: '/dispatch-pod',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchReportsRoute = DispatchReportsRouteImport.update({
  id: '/dispatch-reports',
  path: '/dispatch-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchTransitRoute = DispatchTransitRouteImport.update({
  id: '/dispatch-transit',
  path: '/dispatch-transit',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchTransportAllocationRoute =
  DispatchTransportAllocationRouteImport.update({
    id: '/dispatch-transport-allocation',
    path: '/dispatch-transport-allocation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DispatchVehiclesRoute = DispatchVehiclesRouteImport.update({
  id: '/dispatch-vehicles',
  path: '/dispatch-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const DockManagementRoute = DockManagementRouteImport.update({
  id: '/dock-management',
  path: '/dock-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DockMasterRoute = DockMasterRouteImport.update({
  id: '/dock-master',
  path: '/dock-master',
  getParentRoute: () => rootRouteImport,
} as any)
const GateDashboardRoute = GateDashboardRouteImport.update({
  id: '/gate-dashboard',
  path: '/gate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager-dashboard',
  path: '/manager-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoreRoute = MyStoreRouteImport.update({
  id: '/my-store',
  path: '/my-store',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSupplierRoute = NewSupplierRouteImport.update({
  id: '/new-supplier',
  path: '/new-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PutawayTasksRoute = PutawayTasksRouteImport.update({
  id: '/putaway-tasks',
  path: '/putaway-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier-dashboard',
  path: '/supplier-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UnscheduledArrivalsRoute = UnscheduledArrivalsRouteImport.update({
  id: '/unscheduled-arrivals',
  path: '/unscheduled-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleExitRoute = VehicleExitRouteImport.update({
  id: '/vehicle-exit',
  path: '/vehicle-exit',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleQueueRoute = VehicleQueueRouteImport.update({
  id: '/vehicle-queue',
  path: '/vehicle-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseDashboardRoute = WarehouseDashboardRouteImport.update({
  id: '/warehouse-dashboard',
  path: '/warehouse-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyFinishedGoodsRoute = AssemblyFinishedGoodsRouteImport.update({
  id: '/assembly/finished-goods',
  path: '/assembly/finished-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyMaterialRequestsRoute =
  AssemblyMaterialRequestsRouteImport.update({
    id: '/assembly/material-requests',
    path: '/assembly/material-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyOrdersRoute = AssemblyOrdersRouteImport.update({
  id: '/assembly/orders',
  path: '/assembly/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyProductionRoute = AssemblyProductionRouteImport.update({
  id: '/assembly/production',
  path: '/assembly/production',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyQualityRoute = AssemblyQualityRouteImport.update({
  id: '/assembly/quality',
  path: '/assembly/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyRequestsRoute = AssemblyRequestsRouteImport.update({
  id: '/assembly/requests',
  path: '/assembly/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PoCodeRoute = PoCodeRouteImport.update({
  id: '/po/$code',
  path: '/po/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseAssemblyRequisitionsRoute =
  WarehouseAssemblyRequisitionsRouteImport.update({
    id: '/warehouse/assembly-requisitions',
    path: '/warehouse/assembly-requisitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseDispatchTrackingRoute =
  WarehouseDispatchTrackingRouteImport.update({
    id: '/warehouse/dispatch-tracking',
    path: '/warehouse/dispatch-tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseFinishedGoodsRequestsRoute =
  WarehouseFinishedGoodsRequestsRouteImport.update({
    id: '/warehouse/finished-goods-requests',
    path: '/warehouse/finished-goods-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseFinishedGoodsStoreRoute =
  WarehouseFinishedGoodsStoreRouteImport.update({
    id: '/warehouse/finished-goods-store',
    path: '/warehouse/finished-goods-store',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseMaterialRequestsRoute =
  WarehouseMaterialRequestsRouteImport.update({
    id: '/warehouse/material-requests',
    path: '/warehouse/material-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseMaterialsRoute = WarehouseMaterialsRouteImport.update({
  id: '/warehouse/materials',
  path: '/warehouse/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseQuarantineRoute = WarehouseQuarantineRouteImport.update({
  id: '/warehouse/quarantine',
  path: '/warehouse/quarantine',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseStoresRoute = WarehouseStoresRouteImport.update({
  id: '/warehouse/stores',
  path: '/warehouse/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierAsnsNewRoute = SupplierAsnsNewRouteImport.update({
  id: '/supplier/asns/new',
  path: '/supplier/asns/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-drivers': typeof DispatchDriversRoute
  '/dispatch-exceptions': typeof DispatchExceptionsRoute
  '/dispatch-gate-exit': typeof DispatchGateExitRoute
  '/dispatch-gate-out': typeof DispatchGateOutRoute
  '/dispatch-loading': typeof DispatchLoadingRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/dispatch-picking-packing': typeof DispatchPickingPackingRoute
  '/dispatch-pod': typeof DispatchPodRoute
  '/dispatch-reports': typeof DispatchReportsRoute
  '/dispatch-transit': typeof DispatchTransitRoute
  '/dispatch-transport-allocation': typeof DispatchTransportAllocationRoute
  '/dispatch-vehicles': typeof DispatchVehiclesRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/master-data': typeof MasterDataRoute
  '/my-store': typeof MyStoreRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/assembly/finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly/material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly/orders': typeof AssemblyOrdersRoute
  '/assembly/production': typeof AssemblyProductionRoute
  '/assembly/quality': typeof AssemblyQualityRoute
  '/assembly/requests': typeof AssemblyRequestsRoute
  '/po/$code': typeof PoCodeRoute
  '/q/$code': typeof QCodeRoute
  '/warehouse/assembly-requisitions': typeof WarehouseAssemblyRequisitionsRoute
  '/warehouse/dispatch-tracking': typeof WarehouseDispatchTrackingRoute
  '/warehouse/finished-goods-requests': typeof WarehouseFinishedGoodsRequestsRoute
  '/warehouse/finished-goods-store': typeof WarehouseFinishedGoodsStoreRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/warehouse/quarantine': typeof WarehouseQuarantineRoute
  '/warehouse/stores': typeof WarehouseStoresRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-drivers': typeof DispatchDriversRoute
  '/dispatch-exceptions': typeof DispatchExceptionsRoute
  '/dispatch-gate-exit': typeof DispatchGateExitRoute
  '/dispatch-gate-out': typeof DispatchGateOutRoute
  '/dispatch-loading': typeof DispatchLoadingRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/dispatch-picking-packing': typeof DispatchPickingPackingRoute
  '/dispatch-pod': typeof DispatchPodRoute
  '/dispatch-reports': typeof DispatchReportsRoute
  '/dispatch-transit': typeof DispatchTransitRoute
  '/dispatch-transport-allocation': typeof DispatchTransportAllocationRoute
  '/dispatch-vehicles': typeof DispatchVehiclesRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/master-data': typeof MasterDataRoute
  '/my-store': typeof MyStoreRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/assembly/finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly/material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly/orders': typeof AssemblyOrdersRoute
  '/assembly/production': typeof AssemblyProductionRoute
  '/assembly/quality': typeof AssemblyQualityRoute
  '/assembly/requests': typeof AssemblyRequestsRoute
  '/po/$code': typeof PoCodeRoute
  '/q/$code': typeof QCodeRoute
  '/warehouse/assembly-requisitions': typeof WarehouseAssemblyRequisitionsRoute
  '/warehouse/dispatch-tracking': typeof WarehouseDispatchTrackingRoute
  '/warehouse/finished-goods-requests': typeof WarehouseFinishedGoodsRequestsRoute
  '/warehouse/finished-goods-store': typeof WarehouseFinishedGoodsStoreRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/warehouse/quarantine': typeof WarehouseQuarantineRoute
  '/warehouse/stores': typeof WarehouseStoresRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-drivers': typeof DispatchDriversRoute
  '/dispatch-exceptions': typeof DispatchExceptionsRoute
  '/dispatch-gate-exit': typeof DispatchGateExitRoute
  '/dispatch-gate-out': typeof DispatchGateOutRoute
  '/dispatch-loading': typeof DispatchLoadingRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/dispatch-picking-packing': typeof DispatchPickingPackingRoute
  '/dispatch-pod': typeof DispatchPodRoute
  '/dispatch-reports': typeof DispatchReportsRoute
  '/dispatch-transit': typeof DispatchTransitRoute
  '/dispatch-transport-allocation': typeof DispatchTransportAllocationRoute
  '/dispatch-vehicles': typeof DispatchVehiclesRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/master-data': typeof MasterDataRoute
  '/my-store': typeof MyStoreRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/assembly/finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly/material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly/orders': typeof AssemblyOrdersRoute
  '/assembly/production': typeof AssemblyProductionRoute
  '/assembly/quality': typeof AssemblyQualityRoute
  '/assembly/requests': typeof AssemblyRequestsRoute
  '/po/$code': typeof PoCodeRoute
  '/q/$code': typeof QCodeRoute
  '/warehouse/assembly-requisitions': typeof WarehouseAssemblyRequisitionsRoute
  '/warehouse/dispatch-tracking': typeof WarehouseDispatchTrackingRoute
  '/warehouse/finished-goods-requests': typeof WarehouseFinishedGoodsRequestsRoute
  '/warehouse/finished-goods-store': typeof WarehouseFinishedGoodsStoreRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/warehouse/quarantine': typeof WarehouseQuarantineRoute
  '/warehouse/stores': typeof WarehouseStoresRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assembly-dashboard'
    | '/damage-claims'
    | '/dispatch'
    | '/dispatch-drivers'
    | '/dispatch-exceptions'
    | '/dispatch-gate-exit'
    | '/dispatch-gate-out'
    | '/dispatch-loading'
    | '/dispatch-orders'
    | '/dispatch-picking-packing'
    | '/dispatch-pod'
    | '/dispatch-reports'
    | '/dispatch-transit'
    | '/dispatch-transport-allocation'
    | '/dispatch-vehicles'
    | '/dock-management'
    | '/dock-master'
    | '/gate-dashboard'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/master-data'
    | '/my-store'
    | '/new-supplier'
    | '/notifications'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/warehouse-dashboard'
    | '/admin/users'
    | '/assembly/finished-goods'
    | '/assembly/material-requests'
    | '/assembly/orders'
    | '/assembly/production'
    | '/assembly/quality'
    | '/assembly/requests'
    | '/po/$code'
    | '/q/$code'
    | '/warehouse/assembly-requisitions'
    | '/warehouse/dispatch-tracking'
    | '/warehouse/finished-goods-requests'
    | '/warehouse/finished-goods-store'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/warehouse/quarantine'
    | '/warehouse/stores'
    | '/supplier/asns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assembly-dashboard'
    | '/damage-claims'
    | '/dispatch'
    | '/dispatch-drivers'
    | '/dispatch-exceptions'
    | '/dispatch-gate-exit'
    | '/dispatch-gate-out'
    | '/dispatch-loading'
    | '/dispatch-orders'
    | '/dispatch-picking-packing'
    | '/dispatch-pod'
    | '/dispatch-reports'
    | '/dispatch-transit'
    | '/dispatch-transport-allocation'
    | '/dispatch-vehicles'
    | '/dock-management'
    | '/dock-master'
    | '/gate-dashboard'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/master-data'
    | '/my-store'
    | '/new-supplier'
    | '/notifications'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/warehouse-dashboard'
    | '/admin/users'
    | '/assembly/finished-goods'
    | '/assembly/material-requests'
    | '/assembly/orders'
    | '/assembly/production'
    | '/assembly/quality'
    | '/assembly/requests'
    | '/po/$code'
    | '/q/$code'
    | '/warehouse/assembly-requisitions'
    | '/warehouse/dispatch-tracking'
    | '/warehouse/finished-goods-requests'
    | '/warehouse/finished-goods-store'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/warehouse/quarantine'
    | '/warehouse/stores'
    | '/supplier/asns/new'
  id:
    | '__root__'
    | '/'
    | '/assembly-dashboard'
    | '/damage-claims'
    | '/dispatch'
    | '/dispatch-drivers'
    | '/dispatch-exceptions'
    | '/dispatch-gate-exit'
    | '/dispatch-gate-out'
    | '/dispatch-loading'
    | '/dispatch-orders'
    | '/dispatch-picking-packing'
    | '/dispatch-pod'
    | '/dispatch-reports'
    | '/dispatch-transit'
    | '/dispatch-transport-allocation'
    | '/dispatch-vehicles'
    | '/dock-management'
    | '/dock-master'
    | '/gate-dashboard'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/manager-dashboard'
    | '/master-data'
    | '/my-store'
    | '/new-supplier'
    | '/notifications'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/warehouse-dashboard'
    | '/admin/users'
    | '/assembly/finished-goods'
    | '/assembly/material-requests'
    | '/assembly/orders'
    | '/assembly/production'
    | '/assembly/quality'
    | '/assembly/requests'
    | '/po/$code'
    | '/q/$code'
    | '/warehouse/assembly-requisitions'
    | '/warehouse/dispatch-tracking'
    | '/warehouse/finished-goods-requests'
    | '/warehouse/finished-goods-store'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/warehouse/quarantine'
    | '/warehouse/stores'
    | '/supplier/asns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssemblyDashboardRoute: typeof AssemblyDashboardRoute
  DamageClaimsRoute: typeof DamageClaimsRoute
  DispatchRoute: typeof DispatchRoute
  DispatchDriversRoute: typeof DispatchDriversRoute
  DispatchExceptionsRoute: typeof DispatchExceptionsRoute
  DispatchGateExitRoute: typeof DispatchGateExitRoute
  DispatchGateOutRoute: typeof DispatchGateOutRoute
  DispatchLoadingRoute: typeof DispatchLoadingRoute
  DispatchOrdersRoute: typeof DispatchOrdersRoute
  DispatchPickingPackingRoute: typeof DispatchPickingPackingRoute
  DispatchPodRoute: typeof DispatchPodRoute
  DispatchReportsRoute: typeof DispatchReportsRoute
  DispatchTransitRoute: typeof DispatchTransitRoute
  DispatchTransportAllocationRoute: typeof DispatchTransportAllocationRoute
  DispatchVehiclesRoute: typeof DispatchVehiclesRoute
  DockManagementRoute: typeof DockManagementRoute
  DockMasterRoute: typeof DockMasterRoute
  GateDashboardRoute: typeof GateDashboardRoute
  GrnRoute: typeof GrnRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  MasterDataRoute: typeof MasterDataRoute
  MyStoreRoute: typeof MyStoreRoute
  NewSupplierRoute: typeof NewSupplierRoute
  NotificationsRoute: typeof NotificationsRoute
  PutawayTasksRoute: typeof PutawayTasksRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  UnscheduledArrivalsRoute: typeof UnscheduledArrivalsRoute
  VehicleExitRoute: typeof VehicleExitRoute
  VehicleQueueRoute: typeof VehicleQueueRoute
  WarehouseDashboardRoute: typeof WarehouseDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AssemblyFinishedGoodsRoute: typeof AssemblyFinishedGoodsRoute
  AssemblyMaterialRequestsRoute: typeof AssemblyMaterialRequestsRoute
  AssemblyOrdersRoute: typeof AssemblyOrdersRoute
  AssemblyProductionRoute: typeof AssemblyProductionRoute
  AssemblyQualityRoute: typeof AssemblyQualityRoute
  AssemblyRequestsRoute: typeof AssemblyRequestsRoute
  PoCodeRoute: typeof PoCodeRoute
  QCodeRoute: typeof QCodeRoute
  WarehouseAssemblyRequisitionsRoute: typeof WarehouseAssemblyRequisitionsRoute
  WarehouseDispatchTrackingRoute: typeof WarehouseDispatchTrackingRoute
  WarehouseFinishedGoodsRequestsRoute: typeof WarehouseFinishedGoodsRequestsRoute
  WarehouseFinishedGoodsStoreRoute: typeof WarehouseFinishedGoodsStoreRoute
  WarehouseMaterialRequestsRoute: typeof WarehouseMaterialRequestsRoute
  WarehouseMaterialsRoute: typeof WarehouseMaterialsRoute
  WarehouseQuarantineRoute: typeof WarehouseQuarantineRoute
  WarehouseStoresRoute: typeof WarehouseStoresRoute
  SupplierAsnsNewRoute: typeof SupplierAsnsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-dashboard': {
      id: '/assembly-dashboard'
      path: '/assembly-dashboard'
      fullPath: '/assembly-dashboard'
      preLoaderRoute: typeof AssemblyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-claims': {
      id: '/damage-claims'
      path: '/damage-claims'
      fullPath: '/damage-claims'
      preLoaderRoute: typeof DamageClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-drivers': {
      id: '/dispatch-drivers'
      path: '/dispatch-drivers'
      fullPath: '/dispatch-drivers'
      preLoaderRoute: typeof DispatchDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-exceptions': {
      id: '/dispatch-exceptions'
      path: '/dispatch-exceptions'
      fullPath: '/dispatch-exceptions'
      preLoaderRoute: typeof DispatchExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-gate-exit': {
      id: '/dispatch-gate-exit'
      path: '/dispatch-gate-exit'
      fullPath: '/dispatch-gate-exit'
      preLoaderRoute: typeof DispatchGateExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-gate-out': {
      id: '/dispatch-gate-out'
      path: '/dispatch-gate-out'
      fullPath: '/dispatch-gate-out'
      preLoaderRoute: typeof DispatchGateOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-loading': {
      id: '/dispatch-loading'
      path: '/dispatch-loading'
      fullPath: '/dispatch-loading'
      preLoaderRoute: typeof DispatchLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-orders': {
      id: '/dispatch-orders'
      path: '/dispatch-orders'
      fullPath: '/dispatch-orders'
      preLoaderRoute: typeof DispatchOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-picking-packing': {
      id: '/dispatch-picking-packing'
      path: '/dispatch-picking-packing'
      fullPath: '/dispatch-picking-packing'
      preLoaderRoute: typeof DispatchPickingPackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-pod': {
      id: '/dispatch-pod'
      path: '/dispatch-pod'
      fullPath: '/dispatch-pod'
      preLoaderRoute: typeof DispatchPodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-reports': {
      id: '/dispatch-reports'
      path: '/dispatch-reports'
      fullPath: '/dispatch-reports'
      preLoaderRoute: typeof DispatchReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-transit': {
      id: '/dispatch-transit'
      path: '/dispatch-transit'
      fullPath: '/dispatch-transit'
      preLoaderRoute: typeof DispatchTransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-transport-allocation': {
      id: '/dispatch-transport-allocation'
      path: '/dispatch-transport-allocation'
      fullPath: '/dispatch-transport-allocation'
      preLoaderRoute: typeof DispatchTransportAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-vehicles': {
      id: '/dispatch-vehicles'
      path: '/dispatch-vehicles'
      fullPath: '/dispatch-vehicles'
      preLoaderRoute: typeof DispatchVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-management': {
      id: '/dock-management'
      path: '/dock-management'
      fullPath: '/dock-management'
      preLoaderRoute: typeof DockManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-master': {
      id: '/dock-master'
      path: '/dock-master'
      fullPath: '/dock-master'
      preLoaderRoute: typeof DockMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-dashboard': {
      id: '/gate-dashboard'
      path: '/gate-dashboard'
      fullPath: '/gate-dashboard'
      preLoaderRoute: typeof GateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-dashboard': {
      id: '/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-store': {
      id: '/my-store'
      path: '/my-store'
      fullPath: '/my-store'
      preLoaderRoute: typeof MyStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-supplier': {
      id: '/new-supplier'
      path: '/new-supplier'
      fullPath: '/new-supplier'
      preLoaderRoute: typeof NewSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putaway-tasks': {
      id: '/putaway-tasks'
      path: '/putaway-tasks'
      fullPath: '/putaway-tasks'
      preLoaderRoute: typeof PutawayTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-dashboard': {
      id: '/supplier-dashboard'
      path: '/supplier-dashboard'
      fullPath: '/supplier-dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unscheduled-arrivals': {
      id: '/unscheduled-arrivals'
      path: '/unscheduled-arrivals'
      fullPath: '/unscheduled-arrivals'
      preLoaderRoute: typeof UnscheduledArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-exit': {
      id: '/vehicle-exit'
      path: '/vehicle-exit'
      fullPath: '/vehicle-exit'
      preLoaderRoute: typeof VehicleExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-queue': {
      id: '/vehicle-queue'
      path: '/vehicle-queue'
      fullPath: '/vehicle-queue'
      preLoaderRoute: typeof VehicleQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-dashboard': {
      id: '/warehouse-dashboard'
      path: '/warehouse-dashboard'
      fullPath: '/warehouse-dashboard'
      preLoaderRoute: typeof WarehouseDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/finished-goods': {
      id: '/assembly/finished-goods'
      path: '/assembly/finished-goods'
      fullPath: '/assembly/finished-goods'
      preLoaderRoute: typeof AssemblyFinishedGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/material-requests': {
      id: '/assembly/material-requests'
      path: '/assembly/material-requests'
      fullPath: '/assembly/material-requests'
      preLoaderRoute: typeof AssemblyMaterialRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/orders': {
      id: '/assembly/orders'
      path: '/assembly/orders'
      fullPath: '/assembly/orders'
      preLoaderRoute: typeof AssemblyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/production': {
      id: '/assembly/production'
      path: '/assembly/production'
      fullPath: '/assembly/production'
      preLoaderRoute: typeof AssemblyProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/quality': {
      id: '/assembly/quality'
      path: '/assembly/quality'
      fullPath: '/assembly/quality'
      preLoaderRoute: typeof AssemblyQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly/requests': {
      id: '/assembly/requests'
      path: '/assembly/requests'
      fullPath: '/assembly/requests'
      preLoaderRoute: typeof AssemblyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$code': {
      id: '/po/$code'
      path: '/po/$code'
      fullPath: '/po/$code'
      preLoaderRoute: typeof PoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/assembly-requisitions': {
      id: '/warehouse/assembly-requisitions'
      path: '/warehouse/assembly-requisitions'
      fullPath: '/warehouse/assembly-requisitions'
      preLoaderRoute: typeof WarehouseAssemblyRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/dispatch-tracking': {
      id: '/warehouse/dispatch-tracking'
      path: '/warehouse/dispatch-tracking'
      fullPath: '/warehouse/dispatch-tracking'
      preLoaderRoute: typeof WarehouseDispatchTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/finished-goods-requests': {
      id: '/warehouse/finished-goods-requests'
      path: '/warehouse/finished-goods-requests'
      fullPath: '/warehouse/finished-goods-requests'
      preLoaderRoute: typeof WarehouseFinishedGoodsRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/finished-goods-store': {
      id: '/warehouse/finished-goods-store'
      path: '/warehouse/finished-goods-store'
      fullPath: '/warehouse/finished-goods-store'
      preLoaderRoute: typeof WarehouseFinishedGoodsStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/material-requests': {
      id: '/warehouse/material-requests'
      path: '/warehouse/material-requests'
      fullPath: '/warehouse/material-requests'
      preLoaderRoute: typeof WarehouseMaterialRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/materials': {
      id: '/warehouse/materials'
      path: '/warehouse/materials'
      fullPath: '/warehouse/materials'
      preLoaderRoute: typeof WarehouseMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/quarantine': {
      id: '/warehouse/quarantine'
      path: '/warehouse/quarantine'
      fullPath: '/warehouse/quarantine'
      preLoaderRoute: typeof WarehouseQuarantineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/stores': {
      id: '/warehouse/stores'
      path: '/warehouse/stores'
      fullPath: '/warehouse/stores'
      preLoaderRoute: typeof WarehouseStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/asns/new': {
      id: '/supplier/asns/new'
      path: '/supplier/asns/new'
      fullPath: '/supplier/asns/new'
      preLoaderRoute: typeof SupplierAsnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssemblyDashboardRoute: AssemblyDashboardRoute,
  DamageClaimsRoute: DamageClaimsRoute,
  DispatchRoute: DispatchRoute,
  DispatchDriversRoute: DispatchDriversRoute,
  DispatchExceptionsRoute: DispatchExceptionsRoute,
  DispatchGateExitRoute: DispatchGateExitRoute,
  DispatchGateOutRoute: DispatchGateOutRoute,
  DispatchLoadingRoute: DispatchLoadingRoute,
  DispatchOrdersRoute: DispatchOrdersRoute,
  DispatchPickingPackingRoute: DispatchPickingPackingRoute,
  DispatchPodRoute: DispatchPodRoute,
  DispatchReportsRoute: DispatchReportsRoute,
  DispatchTransitRoute: DispatchTransitRoute,
  DispatchTransportAllocationRoute: DispatchTransportAllocationRoute,
  DispatchVehiclesRoute: DispatchVehiclesRoute,
  DockManagementRoute: DockManagementRoute,
  DockMasterRoute: DockMasterRoute,
  GateDashboardRoute: GateDashboardRoute,
  GrnRoute: GrnRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  MasterDataRoute: MasterDataRoute,
  MyStoreRoute: MyStoreRoute,
  NewSupplierRoute: NewSupplierRoute,
  NotificationsRoute: NotificationsRoute,
  PutawayTasksRoute: PutawayTasksRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  UnscheduledArrivalsRoute: UnscheduledArrivalsRoute,
  VehicleExitRoute: VehicleExitRoute,
  VehicleQueueRoute: VehicleQueueRoute,
  WarehouseDashboardRoute: WarehouseDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AssemblyFinishedGoodsRoute: AssemblyFinishedGoodsRoute,
  AssemblyMaterialRequestsRoute: AssemblyMaterialRequestsRoute,
  AssemblyOrdersRoute: AssemblyOrdersRoute,
  AssemblyProductionRoute: AssemblyProductionRoute,
  AssemblyQualityRoute: AssemblyQualityRoute,
  AssemblyRequestsRoute: AssemblyRequestsRoute,
  PoCodeRoute: PoCodeRoute,
  QCodeRoute: QCodeRoute,
  WarehouseAssemblyRequisitionsRoute: WarehouseAssemblyRequisitionsRoute,
  WarehouseDispatchTrackingRoute: WarehouseDispatchTrackingRoute,
  WarehouseFinishedGoodsRequestsRoute: WarehouseFinishedGoodsRequestsRoute,
  WarehouseFinishedGoodsStoreRoute: WarehouseFinishedGoodsStoreRoute,
  WarehouseMaterialRequestsRoute: WarehouseMaterialRequestsRoute,
  WarehouseMaterialsRoute: WarehouseMaterialsRoute,
  WarehouseQuarantineRoute: WarehouseQuarantineRoute,
  WarehouseStoresRoute: WarehouseStoresRoute,
  SupplierAsnsNewRoute: SupplierAsnsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
